name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-node@v4"
        with:
          node-version: 20
          cache: npm
      - name: install
        run: npm ci
      - name: test
        run: npm test
  slither:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-node@v4"
        with:
          node-version: 20
          cache: npm
      - name: install
        run: npm ci
      - name: compile
        run: npx hardhat compile
      - name: install slither
        run: pip3 install slither-analyzer
      - name: run slither
        run: slither . --filter-paths "node_modules|fhevmTemp" --exclude naming-convention,solc-version --compile-force-framework hardhat --ignore-compile
